name: tests

on:
    push:
        branches: [ main ]

    pull_request:
        branches: [ main ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2

            - name: compile
            run: make

            - name: test
            run: make tests
